from config import (EQUIPO, VERSION, FECHA)

def show_help():
    print("[ ┏┓┏┓┏┓  ┳┳┳  ]========================================================")
    print("[ ┣┫┃ ┃┃━━┃┃┃  ]================= Comandos disponibles =================")
    print("[ ┛┗┗┛┗┻  ┻┻┻  ]========================================================")
    print("--- General ---")
    print("ESC ?\t\t\t\tAyuda")
    print("ESC e\t\t\t\tDatos y versión del equipo")
    print("--- Config ---")
    print("ESC s\t\t\t\tMostrar secuencia de inicio")
    print("ESC S [w]\t\t\tHabilita/Deshabilita servicio seleccionado")
    print("--- RTC ---")
    print("ESC H [yyyy,mm,dd,hh,mm,ss]\tSetea fecha y hora en el RTC")
    print("ESC h\t\t\t\tLee fecha y hora desde el RTC")
    print("--- WIFI ---")
    print("ESC W s [SSID]\t\t\tSetea SSID")
    print("ESC W p [password]\t\tSetea password del WiFi")
    print("ESC W c\t\t\t\tConecta a la red WiFi")
    print("ESC W d\t\t\t\tDesconecta de la red WiFi")

def show_version():
    print(" $$$$$$\   $$$$$$\   $$$$$$\        $$$$$$\ $$$$$$\ $$$$$$\ ")
    print("$$  __$$\ $$  __$$\ $$  __$$\       \_$$  _|\_$$  _|\_$$  _|")
    print("$$ /  $$ |$$ /  \__|$$ /  $$ |        $$ |    $$ |    $$ |  ")
    print("$$$$$$$$ |$$ |      $$ |  $$ |$$$$$$\ $$ |    $$ |    $$ |  ")
    print("$$  __$$ |$$ |      $$ |  $$ |\______|$$ |    $$ |    $$ |  ")
    print("$$ |  $$ |$$ |  $$\ $$ $$\$$ |        $$ |    $$ |    $$ |  ")
    print("$$ |  $$ |\$$$$$$  |\$$$$$$ /       $$$$$$\ $$$$$$\ $$$$$$\ ")
    print("\__|  \__| \______/  \___$$$\       \______|\______|\______|")
    print("                         \___|                              ")
    print(f"Equipo: {EQUIPO}")
    print(f"Versión: {VERSION}")
    print(f"Fecha: {FECHA}")
